### PR TITLE
[1.8.9] Fix Crashes+Chinese Translate

### PR DESCRIPTION
**Pull request by HowardZHY**
**Please make a New 1.8.9 Branch**

### CODE REVIEW

**Comment by ate47** [comment]
The computer where the 1.8.8 version was is finally available to me, I've uploaded the 1.8.8 branch (it's the same as the 1.8.9)

It's probably different from the latest older version so can you rebase your changes to this one?

And can you [squash your commits](https://rdf4j.org/documentation/developer/squashing/) if you can?

**Comment by HowardZHY** [comment]
wdym? My 1.8.9 branch is based on https://github.com/ate47/AdvancedCreativeTab/tree/e4801181fb0e095eda3975f42ee6caf22f7457dc
's src-1.8.8

**Comment by ate47** [comment]
Ok, I through it wasn't available, but I created a different branch for all the versions, so it will be prettier and less annoying if someone wants to search for a change

**Comment by HowardZHY** [comment]
Let me commit to the branch you uploaded instead

**Pull request closed without merging**
